version: "3"
services:
  app:
    build:
      context: .
      dockerfile: build/docker/app/Dockerfile
      args:
        BUILD_ENV: dev
    volumes:
      - ./:/var/www/html

  nginx:
    build:
      dockerfile: build/docker/nginx/Dockerfile
      context: .
    volumes:
      - ./public:/usr/share/nginx/html
    environment:
      BACKEND_SERVICE: app
      CACHE_ZONE: 'off'
    ports:
      - 80:80
    depends_on:
      - app
      
  database:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    volumes:
      - btbw_data:/var/lib/mysql

volumes:
  btbw_data: